services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: chookpedia
      POSTGRES_USER: malcolmp
    image: "postgres:17-alpine"
